TawredatProject/Areas/Admin/Controllers/SupplierCategoryController.cs
using BL;
using Domains;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Data;
using System.Threading.Tasks;
using System;
using TawredatProject.Models;
using Microsoft.AspNetCore.Authorization;
using System.Linq;

namespace TawredatProject.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class SupplierCategoryController : Controller
    {
        SupplierCategoryService supplierCategoryService;

        TawredatDbContext ctx;
        public SupplierCategoryController(SupplierCategoryService SupplierCategoryService, TawredatDbContext context)
        {

            supplierCategoryService = SupplierCategoryService;
            ctx = context;

        }
        [Authorize(Roles = "Admin, اقسام التجار")]
        public IActionResult Index()
        {

            HomePageModel model = new HomePageModel();
            model.lstSupplierCategories = supplierCategoryService.getAll();

            return View(model);


        }




        [HttpPost]
        public async Task<IActionResult> Save(TbSupplierCategory ITEM, int id, List<IFormFile> files)
        {
            if (ITEM.SupplierCategoryId == null)
            {


                if (ModelState.IsValid)
                {
                    //foreach (var file in files)
                    //{
                    //    if (file.Length > 0)
                    //    {
                    //        string ImageName = Guid.NewGuid().ToString() + ".jpg";
                    //        var filePaths = Path.Combine(Directory.GetCurrentDirectory(), @"wwwroot\Uploads", ImageName);
                    //        using (var stream = System.IO.File.Create(filePaths))
                    //        {
                    //            await file.CopyToAsync(stream);
                    //        }
                    //        ITEM.ab = ImageName;
                    //    }
                    //}





                    var result = supplierCategoryService.Add(ITEM);
                    if (result == true)
                    {
                        TempData[SD.Success] = "Supplier Category  Profile successfully Created.";
                    }
                    else
                    {
                        TempData[SD.Error] = "Error in Supplier Category  Profile  Creating.";
                    }


                }


            }
            else
            {
                if (ModelState.IsValid)
                {
                    //foreach (var file in files)
                    //{
                    //    if (file.Length > 0)
                    //    {
                    //        string ImageName = Guid.NewGuid().ToString() + ".jpg";
                    //        var filePaths = Path.Combine(Directory.GetCurrentDirectory(), @"wwwroot\Uploads", ImageName);
                    //        using (var stream = System.IO.File.Create(filePaths))
                    //        {
                    //            await file.CopyToAsync(stream);
                    //        }
                    //        ITEM.MainConsultingImage = ImageName;
                    //    }
                    //}






                    var result = supplierCategoryService.Edit(ITEM);
                    if (result == true)
                    {
                        TempData[SD.Success] = "Supplier Category  Profile successfully Updated.";
                    }
                    else
                    {
                        TempData[SD.Error] = "Error in Supplier Category  Profile  Updating.";
                    }

                }
            }




            HomePageModel model = new HomePageModel();
            model.lstSupplierCategories = supplierCategoryService.getAll();
            return View("Index", model);
        }




        [Authorize(Roles = "Admin,حذف  اقسام التجار")]
        public IActionResult Delete(Guid id)
        {

            TbSupplierCategory oldItem = ctx.TbSupplierCategories.Where(a => a.SupplierCategoryId == id).FirstOrDefault();



            var result = supplierCategoryService.Delete(oldItem);
            if (result == true)
            {
                TempData[SD.Success] = "Supplier Category  Profile successfully Removed.";
            }
            else
            {
                TempData[SD.Error] = "Error in Supplier Category  Profile  Removing.";
            }

            HomePageModel model = new HomePageModel();
            model.lstSupplierCategories = supplierCategoryService.getAll();
            return View("Index", model);



        }



        [Authorize(Roles = "Admin, اضافة او تعديل  اقسام التجار")]
        public IActionResult Form(Guid? id)
        {
            TbSupplierCategory oldItem = ctx.TbSupplierCategories.Where(a => a.SupplierCategoryId == id).FirstOrDefault();
            

            return View(oldItem);
        }
    }
}

TawredatProject/Areas/Admin/Views/SupplierCategory/Form.cshtml
@model Domains.TbSupplierCategory
<!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
                <h1>اضافة  اقسام التجار</h1>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#"> اقسام التجار</a></li>
                    <li class="breadcrumb-item active">اضافة  اقسام التجار</li>
            </ol>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <div class="row">
          <!-- left column -->
          <div class="col-md-12">
            <!-- general form elements -->
            <div class="card card-primary">
              <div class="card-header">
               
              </div>
              <!-- /.card-header -->
              <!-- form start -->
                    <form id="form" enctype="multipart/form-data" method="post" role="form" asp-area="Admin" asp-controller="SupplierCategory" asp-action="Save">
                <div class="card-body">
                            <div asp-validation-summary="All" class="text-danger"></div>
                  <div class="form-group">
                                <input type="hidden"  asp-for="SupplierCategoryId" >
                                <input type="hidden" asp-for="CreatedDate">
                                <label for="exampleInputEmail1"> اسم قسم التاجر</label>
                                <input type="text" class="form-control" id="exampleInputEmail1" asp-for="SupplierCategoryName" placeholder=" عن اسم قسم التاجر">
                                <span asp-validation-for="SupplierCategoryName" class="text-danger"></span>
                  </div>
                  <div class="form-group">
                                <label for="exampleInputPassword1">وصف قسم التاجر </label>
                                <input type="text" class="form-control" id="exampleInputPassword1" asp-for="SupplierCategoryDescription" placeholder="  وصف قسم التاجر">
                                <span asp-validation-for="SupplierCategoryDescription" class="text-danger"></span>
                  </div>
                
                         
                 
                </div>
                <!-- /.card-body -->

                <div class="card-footer">
                  <button type="submit" class="btn btn-primary">Submit</button>
                </div>
              </form>
            </div>
            <!-- /.card -->

          
            <!-- /.card -->

          </div>
          <!--/.col (left) -->
      
        </div>
        <!-- /.row -->
      </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
<script type="application/javascript">
    var a = document.getElementById("inputGroupFile02");
    a.value= "ahmed.txt";
</script>
@section Scripts{
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
     
    }
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
   @* <script>
        //alert("ahmed");
        const logo = document.getElementById('selectedFile');
        const license = document.getElementById('selectedFiles');
        const form = document.getElementById('form')
        const erroElement = document.getElementById('error')
        const erroElement1 = document.getElementById('error1')
        form.addEventListener('submit',(e)=> 
        {
            //e.preventDefault();
            let messages =[];
            let messages2 = [];
            if (logo.value === '' || logo.value == null) 
            {
                //alert('ahmed');
                messages.push('This field is required');
                erroElement.innerHTML = messages;
            }
            else 
            {
                messages =[];
                erroElement.innerHTML = messages;

            }
            if (license.value === '' || license.value == null) {
                //alert('ahmed');
                messages2.push('This field is required');
                erroElement1.innerHTML = messages2;
            }
            else {
                messages = [];
                erroElement1.innerHTML = messages2;

            }


        });
    </script>*@
    }

TawredatProject/Areas/Admin/Views/SupplierCategory/Index.cshtml
@model TawredatProject.Models.HomePageModel
<!-- Content Header (Page header) -->
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>عرض اقسام التجار</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">اقسام التجار</a></li>
                    <li class="breadcrumb-item active">عرض اقسام التجار</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>

<!-- Main content -->
<section class="content">
    <div class="row">
        <div class="col-12">


            <div class="card">
                <div class="card-header">
                   
                </div>
                <!-- /.card-header -->
                <div class="card-body">
                    <table id="example1" class="table table-bordered table-striped ">
                        <thead>
                            <tr>
                                <th>اسم قسم التاجر</th>
                                <th>تفاصيل قسم التاجر</th>
                                <th>موجهة لمن</th>
                                <th>تعديل</th>

                                <th>حذف</th>
                              
                               
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model.lstSupplierCategories)
                            {

                                <tr>
                                    <td>@item.SupplierCategoryName</td>
                                    <td>
                                        @item.SupplierCategoryDescription
                                    </td>
                                  

                              
                                    <td>
                                        <a asp-area="Admin" asp-controller="SupplierCategory" asp-action="Form" asp-route-id="@item.SupplierCategoryId" class="btn btn-info text-white" style="cursor:pointer">
                                            تعديل
                                        </a>
                                    </td>
                                    <td>
                                        <a asp-area="Admin" asp-controller="SupplierCategory" asp-action="Delete" asp-route-id="@item.SupplierCategoryId" class="btn btn-danger text-white" style="cursor:pointer">
                                            حذف
                                        </a>
                                    </td>
                                  
                                   
                                </tr>

                            }


                        </tbody>
                        <tfoot>
                            <tr>
                                <th>عنوان عن التطبيق</th>
                                <th>تفاصيل عن التطبيق</th>
                                <th>موجهة لمن</th>
                                <th>تعديل</th>

                                <th>حذف</th>
                            </tr>
                        </tfoot>
                    </table>
                </div>
                <!-- /.card-body -->
            </div>
            <!-- /.card -->
        </div>
        <!-- /.col -->
    </div>
    <!-- /.row -->
</section>
<!-- /.content -->