TawredatProject/Areas/Admin/Controllers/CityDeliveryController.cs
using BL;
using Domains;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Data;
using System.Threading.Tasks;
using System;
using TawredatProject.Models;
using Microsoft.AspNetCore.Authorization;
using System.Linq;

namespace TawredatProject.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class CityDeliveryController : Controller
    {
        CityService cityService;
        CityDeliveryService cityDeliveryService;

        TawredatDbContext ctx;
        public CityDeliveryController(CityService CityService, CityDeliveryService CityDeliveryService, TawredatDbContext context)
        {
            cityService = CityService;
            cityDeliveryService = CityDeliveryService;
            ctx = context;

        }
        [Authorize(Roles = "Admin,قيمة الشحن للمدن")]
        public IActionResult Index()
        {

            HomePageModel model = new HomePageModel();
            model.lstCityDeliveryFees = cityDeliveryService.getAll();

            return View(model);


        }




        [HttpPost]
        public async Task<IActionResult> Save(TbCityDeliveryFees ITEM, int id, List<IFormFile> files)
        {
            if (ITEM.CityDeliveryFeesId == null)
            {


                if (ModelState.IsValid)
                {
                    //foreach (var file in files)
                    //{
                    //    if (file.Length > 0)
                    //    {
                    //        string ImageName = Guid.NewGuid().ToString() + ".jpg";
                    //        var filePaths = Path.Combine(Directory.GetCurrentDirectory(), @"wwwroot\Uploads", ImageName);
                    //        using (var stream = System.IO.File.Create(filePaths))
                    //        {
                    //            await file.CopyToAsync(stream);
                    //        }
                    //        ITEM.ab = ImageName;
                    //    }
                    //}





                    var result = cityDeliveryService.Add(ITEM);
                    if (result == true)
                    {
                        TempData[SD.Success] = "City Delivery Fess Profile successfully Created.";
                    }
                    else
                    {
                        TempData[SD.Error] = "Error in City Delivery Fess Profile  Creating.";
                    }


                }


            }
            else
            {
                if (ModelState.IsValid)
                {
                    //foreach (var file in files)
                    //{
                    //    if (file.Length > 0)
                    //    {
                    //        string ImageName = Guid.NewGuid().ToString() + ".jpg";
                    //        var filePaths = Path.Combine(Directory.GetCurrentDirectory(), @"wwwroot\Uploads", ImageName);
                    //        using (var stream = System.IO.File.Create(filePaths))
                    //        {
                    //            await file.CopyToAsync(stream);
                    //        }
                    //        ITEM.MainConsultingImage = ImageName;
                    //    }
                    //}






                    var result = cityDeliveryService.Edit(ITEM);
                    if (result == true)
                    {
                        TempData[SD.Success] = "City Delivery Fess Profile successfully Updated.";
                    }
                    else
                    {
                        TempData[SD.Error] = "Error in City Delivery Fess Profile  Updating.";
                    }

                }
            }




            HomePageModel model = new HomePageModel();
            model.lstCityDeliveryFees = cityDeliveryService.getAll();
            return View("Index", model);
        }




        [Authorize(Roles = "Admin,حذف قيمة الشحن للمدن")]
        public IActionResult Delete(Guid id)
        {

            TbCityDeliveryFees oldItem = ctx.TbCityDeliveryFeess.Where(a => a.CityDeliveryFeesId == id).FirstOrDefault();



            var result = cityDeliveryService.Delete(oldItem);
            if (result == true)
            {
                TempData[SD.Success] = "City Delivery Fess Profile successfully Removed.";
            }
            else
            {
                TempData[SD.Error] = "Error in City Delivery Fess Profile  Removing.";
            }

            HomePageModel model = new HomePageModel();
            model.lstCityDeliveryFees = cityDeliveryService.getAll();
            return View("Index", model);



        }



        [Authorize(Roles = "Admin, اضافة او تعديل قيمة الشحن للمدن")]
        public IActionResult Form(Guid? id)
        {
            TbCityDeliveryFees oldItem = ctx.TbCityDeliveryFeess.Where(a => a.CityDeliveryFeesId == id).FirstOrDefault();

            ViewBag.realCities = cityService.getAll();

            return View(oldItem);
        }
    }
}

TawredatProject/Areas/Admin/Views/CityDelivery/Form.cshtml
@model Domains.TbCityDeliveryFees
<!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
                <h1>اضافة  قيمة الشحن للمدن </h1>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">قيمة الشحن للمدن </a></li>
                    <li class="breadcrumb-item active">اضافة قيمة الشحن للمدن </li>
            </ol>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <div class="row">
          <!-- left column -->
          <div class="col-md-12">
            <!-- general form elements -->
            <div class="card card-primary">
              <div class="card-header">
               
              </div>
              <!-- /.card-header -->
              <!-- form start -->
                    <form id="form" enctype="multipart/form-data" method="post" role="form" asp-area="Admin" asp-controller="CityDelivery" asp-action="Save">
                <div class="card-body">
                            <div asp-validation-summary="All" class="text-danger"></div>


                            <section class="content">
                                <div class="container-fluid">
                                    <!-- SELECT2 EXAMPLE -->
                                    <div class="card card-default">
                                        <div class="card-header">
                                            <h3 class="card-title">اسم المدينة</h3>


                                        </div>
                                        <!-- /.card-header -->
                                        <div class="card-body">
                                            <div class="row">
                                                <div class="col-md-6">
                                                    <div class="form-group">
                                                        <label> اسم المدينة</label>
                                                        <select asp-for="CityId" asp-items="@(new SelectList(ViewBag.realCities , "CityId" , "CityName"))" class="form-control select2" style="width: 100%;" required>
                                                            <option value="">اختر</option>
                                                           


                                                        </select>
                                                        <span asp-validation-for="CityId" class="text-danger"></span>
                                                    </div>

                                                </div>

                                            </div>
                                            <!-- /.row -->
                                        </div>
                                        <!-- /.card-body -->

                                    </div>
                                    <!-- /.card -->

                                </div>
                            </section>





                  <div class="form-group">
                                <input type="hidden" asp-for="CityDeliveryFeesId">
                               
                                <input type="hidden" asp-for="CityName">
                                <input type="hidden" asp-for="CreatedDate">
                                <label for="exampleInputEmail1">قيمة الشحن للمدينة</label>
                                <input type="text" class="form-control" id="exampleInputEmail1" asp-for="DeliveryFees" placeholder=" اسم المدينة">
                                <span asp-validation-for="CityName" class="text-danger"></span>
                  </div>
                 
                 @* <div class="form-group">
                                <label for="exampleInputPassword1">اسم المدينة</label>
                                <input type="text" class="form-control" id="exampleInputPassword1" asp-for="CityName" placeholder="اسم المدينة">
                                <span asp-validation-for="CityName" class="text-danger"></span>
                   </div>*@
                 @* <div class="form-group">

                                <div class="input-group mb-3">
                                    <div class="custom-file">
                                        <label for="exampleInputPassword1">لوجو المكتب</label>
                                        <input  required  type="file" name="files" id="selectedFile" />
                                        <div class="text-danger" id="error"></div>
                                    </div>
                                   
                                </div>
                  </div>*@
                @*  <div class="form-group">

                                <div class="input-group mb-3">
                                    <div class="custom-file">
                                        <label for="exampleInputPassword1">ملف الرخصة</label>
                                        <input  required type="file" name="filess" id="selectedFiles" />
                                        <div class="text-danger" id="error1"></div>
                                    </div>

                                </div>
                   </div>*@
                          
                 
                </div>
                <!-- /.card-body -->

                <div class="card-footer">
                  <button type="submit" class="btn btn-primary">Submit</button>
                </div>
              </form>
            </div>
            <!-- /.card -->

          
            <!-- /.card -->

          </div>
          <!--/.col (left) -->
      
        </div>
        <!-- /.row -->
      </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
<script type="application/javascript">
    var a = document.getElementById("inputGroupFile02");
    a.value= "ahmed.txt";
</script>
@section Scripts{
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
     
    }
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
   @* <script>
        //alert("ahmed");
        const logo = document.getElementById('selectedFile');
        const license = document.getElementById('selectedFiles');
        const form = document.getElementById('form')
        const erroElement = document.getElementById('error')
        const erroElement1 = document.getElementById('error1')
        form.addEventListener('submit',(e)=> 
        {
            //e.preventDefault();
            let messages =[];
            let messages2 = [];
            if (logo.value === '' || logo.value == null) 
            {
                //alert('ahmed');
                messages.push('This field is required');
                erroElement.innerHTML = messages;
            }
            else 
            {
                messages =[];
                erroElement.innerHTML = messages;

            }
            if (license.value === '' || license.value == null) {
                //alert('ahmed');
                messages2.push('This field is required');
                erroElement1.innerHTML = messages2;
            }
            else {
                messages = [];
                erroElement1.innerHTML = messages2;

            }


        });
    </script>*@
    }

TawredatProject/Areas/Admin/Views/CityDelivery/Index.cshtml
@model TawredatProject.Models.HomePageModel
<!-- Content Header (Page header) -->
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>عرض قيمة التوصيل للمدن</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">  قيمة التوصيل للمدن</a></li>
                    <li class="breadcrumb-item active">عرض  قيمة التوصيل للمدن</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>

<!-- Main content -->
<section class="content">
    <div class="row">
        <div class="col-12">


            <div class="card">
                <div class="card-header">
                   
                </div>
                <!-- /.card-header -->
                <div class="card-body">
                    <table id="example1" class="table table-bordered table-striped ">
                        <thead>
                            <tr>
                                <th>اسم  المدينة</th>

                                <th>قيمة الشحن  </th>
                               
                                <th>تعديل</th>

                                <th>حذف</th>
                              
                               
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model.lstCityDeliveryFees)
                            {

                                <tr>
                                    <td>@item.CityName</td>
                                    <td>@item.DeliveryFees</td>
                                  
                                    <td>
                                        <a asp-area="Admin" asp-controller="CityDelivery" asp-action="Form" asp-route-id="@item.CityDeliveryFeesId" class="btn btn-info text-white" style="cursor:pointer">
                                            تعديل
                                        </a>
                                    </td>
                                    <td>
                                        <a asp-area="Admin" asp-controller="CityDelivery" asp-action="Delete" asp-route-id="@item.CityDeliveryFeesId" class="btn btn-danger text-white" style="cursor:pointer">
                                            حذف
                                        </a>
                                    </td>
                                  
                                   
                                </tr>

                            }


                        </tbody>
                        <tfoot>
                            <tr>
                                <th>اسم  المدينة</th>

                                <th>قيمة الشحن  </th>

                                <th>تعديل</th>

                                <th>حذف</th>
                            </tr>
                        </tfoot>
                    </table>
                </div>
                <!-- /.card-body -->
            </div>
            <!-- /.card -->
        </div>
        <!-- /.col -->
    </div>
    <!-- /.row -->
</section>
<!-- /.content -->